---
  - hosts: all
    become: true
    vars:
      ansible_python_interpreter: /usr/bin/python3
  
    tasks:
      - name: Kill processes locking dpkg
        ansible.builtin.shell: |
          fuser -k /var/lib/dpkg/lock /var/lib/apt/lists/lock /var/cache/apt/archives/lock || true
  
      - name: Comment out CD-ROM repository entry
        ansible.builtin.lineinfile:
          path: /etc/apt/sources.list
          regexp: '^deb cdrom:'
          line: '# deb cdrom:[OS Astra Linux 1.7.0 1.7_x86-64 DVD ]/ 1.7_x86-64 contrib main non-free'
          state: present
  
      - name: Ensure repository-base is present
        ansible.builtin.lineinfile:
          path: /etc/apt/sources.list
          line: "deb http://download.astralinux.ru/astra/frozen/1.7_x86-64/1.7.3/uu/2/repository-base 1.7_x86-64 main non-free contrib"
          state: present
          insertafter: EOF
  
      - name: Ensure repository-extended is present
        ansible.builtin.lineinfile:
          path: /etc/apt/sources.list
          line: "deb http://download.astralinux.ru/astra/frozen/1.7_x86-64/1.7.3/uu/2/repository-extended 1.7_x86-64 main contrib non-free"
          state: present
          insertafter: EOF
  
      - name: Fix broken dpkg state
        ansible.builtin.command:
          cmd: dpkg --configure -a
        args:
          warn: false
  
      - name: Update package cache
        ansible.builtin.apt:
          update_cache: yes
  
      - name: Upgrade all packages to latest
        ansible.builtin.apt:
          upgrade: dist
  
      - name: Install python3-pip
        ansible.builtin.apt:
          name: python3-pip
          update_cache: yes
          state: present
  
      - name: Install etcd
        ansible.builtin.apt:
          name: etcd
          update_cache: yes
          state: present
          
      - name: Install setuptools for Python 3
        ansible.builtin.pip:
          name: setuptools
  
      - name: Install multiple Python packages
        ansible.builtin.pip:
          name:
            - psycopg
            - python-etcd
            - etcd3
  
      - name: Install patroni packages with pip3
        ansible.builtin.pip:
          name: patroni
  